export const PRODUCT_004 = {
  id: '004',
  title: 'AI Daily Life Toolkit: 30 Day Challenge',
  subtitle: 'Build AI Habits That Save 10+ Hours Per Week — One Task Per Day',
  type: 'template' as const,
  niche: 'productivity',
  targetAudience: 'professionals, entrepreneurs, students, anyone wanting more productivity',
  pages: 35,
  wordCount: 10000,
  fileFormats: ['PDF'] as string[],
  price: 8.99,
  introduction: `Welcome to the 30-Day AI Challenge. By Day 30, you'll have built real AI habits that save 10+ hours per week. Each day takes 10-15 minutes. All you need is a free ChatGPT account (chat.openai.com) — no tech skills required.

How to use this guide: Each day has one specific task and one exact prompt to copy-paste. Don't modify the prompts at first — use them exactly as written, then customize for your situation. Save prompts that work well to a personal document.

Tools needed: ChatGPT (free), optionally Claude (claude.ai) for longer documents. That's it.`,
  weeks: [
    {
      week: 1,
      theme: 'AI Fundamentals: Your First 7 Wins',
      days: [
        {
          day: 1,
          title: 'Your First Powerful Prompt',
          task: 'Use ChatGPT to create a personalized learning plan for any skill you want to develop.',
          prompt: `"Create a 4-week beginner learning plan for [skill you want to learn]. For each week: 3 specific learning resources (free preferred), one hands-on practice exercise, and one way to measure my progress. My current level: complete beginner. Time available: 30 minutes per day."`,
          timeEstimate: '10 minutes',
          insight: 'The more specific context you give AI, the more useful the output. Notice how "complete beginner, 30 min/day" changes the plan completely.',
        },
        {
          day: 2,
          title: 'The Email Draft Hack',
          task: 'Draft any professional email in 60 seconds using this template.',
          prompt: `"Write a professional email:\nTo: [recipient and their role]\nAbout: [what the email is about]\nTone: [formal/friendly/urgent/appreciative]\nKey points to cover: [point 1], [point 2], [point 3]\nDesired outcome: [what you want them to do]\nMy name: [your name]\n\nKeep it under 150 words. Use a clear subject line."`,
          timeEstimate: '10 minutes',
          insight: 'Use this for every professional email today. Track how much time you save vs writing from scratch.',
        },
        {
          day: 3,
          title: 'Research Anything in 5 Minutes',
          task: 'Use AI to quickly understand any complex topic.',
          prompt: `"Give me a crash course on [topic] in 5 minutes. Structure it as:\n1. What it is in one sentence (no jargon)\n2. Why it matters (real-world impact)\n3. The 5 key concepts I need to know first\n4. Common misconceptions\n5. Where to go deeper (3 specific resources)\n\nAssume I'm intelligent but know nothing about this topic."`,
          timeEstimate: '10 minutes',
          insight: 'This is better than most Google searches — AI synthesizes information and explains relationships between concepts.',
        },
        {
          day: 4,
          title: 'The Document Summarizer',
          task: 'Paste any long document or article and get a structured summary in seconds.',
          prompt: `"Summarize this document/article in exactly this format:\n\n**Main Argument** (1 sentence)\n**Key Points** (5 bullet points, most important first)\n**Surprising or Counterintuitive Insight** (1 thing I wouldn't have expected)\n**Action Items for Me** (2-3 things I can do with this information)\n\nDocument: [paste text here]"`,
          timeEstimate: '10 minutes',
          insight: 'Use this for reports, articles, meeting transcripts, long emails — anything you need to quickly understand without reading every word.',
        },
        {
          day: 5,
          title: 'The Brainstorm Machine',
          task: 'Generate more ideas in 10 minutes than you could in an hour alone.',
          prompt: `"I need to brainstorm [describe your challenge or goal]. Give me 20 ideas — ranging from obvious/safe to creative/unconventional. For each idea, give it a name and one sentence explanation. After the list, mark the 3 you think are most promising with a star and explain why briefly."`,
          timeEstimate: '10 minutes',
          insight: 'Ask for exactly 20 ideas — it forces AI to go beyond obvious answers into creative territory. Always ask which ones it recommends.',
        },
        {
          day: 6,
          title: 'AI Writing Coach',
          task: 'Improve any piece of writing using AI feedback.',
          prompt: `"Review this [type of writing: email/report/bio/post/etc] and give me:\n1. Overall grade (A/B/C/D) with one reason\n2. The strongest part (don't change this)\n3. The weakest part and exactly how to fix it\n4. Two sentences that should be cut or rewritten\n5. One thing that would make this 10x better\n\nThen rewrite the whole piece incorporating your feedback.\n\nText: [paste your writing]"`,
          timeEstimate: '15 minutes',
          insight: 'Always ask AI to critique AND rewrite. The comparison between original and improved shows you exactly what to fix.',
        },
        {
          day: 7,
          title: 'Build Your Personal Prompt Library',
          task: 'Collect your best prompts from days 1-6 into a reusable library.',
          prompt: `"I want to build a personal AI prompt library. Here are the prompts I've used this week that worked well: [paste your favorite prompts from days 1-6]. For each prompt:\n1. Give it a memorable name\n2. Identify the [PLACEHOLDER] variables I should customize each time\n3. Suggest one variation that would be useful to have\n\nFormat as a clean reference document I can copy to Notion or Google Docs."`,
          timeEstimate: '20 minutes',
          insight: 'Your prompt library is your AI superpower. Keep adding to it every week. The best prompts are worth saving forever.',
        },
      ],
    },
    {
      week: 2,
      theme: 'AI for Work: Save 2+ Hours Every Day',
      days: [
        {
          day: 8,
          title: 'Meeting Summary Generator',
          task: 'Turn messy meeting notes into a clean action-oriented summary.',
          prompt: `"Convert these meeting notes into a professional summary:\n\n**Meeting:** [title/topic]\n**Date:** [date]\n**Attendees:** [names]\n\n**Notes:** [paste your raw notes]\n\nFormat the summary as:\n- Key Decisions (bullet list)\n- Action Items (Name: Task, Deadline)\n- Open Questions to Resolve\n- Next Steps\n\nKeep it under 300 words. Make action items crystal clear."`,
          timeEstimate: '10 minutes',
          insight: 'Send this summary to all attendees within 30 minutes of the meeting. It establishes you as organized and drives accountability.',
        },
        {
          day: 9,
          title: 'Report & Presentation Builder',
          task: 'Create a complete report or presentation outline in minutes.',
          prompt: `"Create a complete outline for a [type: report/presentation/proposal] about [topic] for [audience: clients/executives/team/investors].\n\nInclude:\n- Title and subtitle suggestions (3 options)\n- Executive summary (3-4 sentences)\n- 5-7 main sections with subsections\n- Key data points I should include in each section\n- Conclusion and call to action\n\nTone: [professional/conversational/technical]. Length: [X pages/X minutes if presentation]."`,
          timeEstimate: '15 minutes',
          insight: 'Never start from a blank slide or page again. Use this outline as your structure, then fill in your specific data and examples.',
        },
        {
          day: 10,
          title: 'The Decision Helper',
          task: 'Use AI to make a difficult decision more clearly.',
          prompt: `"Help me make a decision. I'm choosing between:\n\nOption A: [describe]\nOption B: [describe]\n[Option C if applicable]\n\nContext: [what matters most to me about this decision, any constraints]\nDeadline: [when I need to decide]\n\nPlease:\n1. Identify the 3 most important criteria for this decision\n2. Score each option 1-10 on each criterion\n3. Identify what I might be overlooking\n4. Give me your recommendation with clear reasoning\n5. Tell me the biggest risk of your recommended option"`,
          timeEstimate: '10 minutes',
          insight: "AI doesn't make the decision — you do. But it often surfaces considerations you hadn't thought of and removes emotional bias.",
        },
        {
          day: 11,
          title: 'Job Application Accelerator',
          task: 'Customize your resume and cover letter for a specific job in 20 minutes.',
          prompt: `"I'm applying for this job:\n\nJOB POSTING: [paste full job description]\n\nMY BACKGROUND: [paste your resume or key experience in 200 words]\n\nPlease:\n1. Identify the 5 most important requirements from the job posting\n2. Match my experience to each requirement (be specific)\n3. Write a targeted cover letter opening paragraph that references the company specifically\n4. List 3 keywords from the posting I should add to my resume\n5. Suggest 2 questions I should ask in the interview"`,
          timeEstimate: '20 minutes',
          insight: 'Custom applications get 3x more interviews than generic ones. This prompt cuts customization time from 2 hours to 20 minutes.',
        },
        {
          day: 12,
          title: 'Data Explainer',
          task: 'Paste any data or spreadsheet excerpt and get plain-English insights.',
          prompt: `"Analyze this data and explain it in plain English:\n\n[paste data, table, or numbers]\n\nTell me:\n1. What the data shows in one sentence\n2. The 3 most important patterns or trends\n3. What's surprising or unexpected\n4. What questions I should ask to understand this better\n5. One chart type that would best visualize this (and why)"`,
          timeEstimate: '10 minutes',
          insight: "AI can't access your actual spreadsheets, but paste 10-20 rows and it can spot patterns humans miss.",
        },
        {
          day: 13,
          title: 'Difficult Conversation Prep',
          task: 'Prepare for a hard conversation with a script and objection responses.',
          prompt: `"Help me prepare for a difficult conversation:\n\nSituation: [describe what happened and with whom]\nMy goal: [what outcome do I want?]\nMy concern: [what am I afraid will happen?]\n\nPlease provide:\n1. An opening statement (2-3 sentences to start the conversation)\n2. 3 ways they might respond and how I should reply to each\n3. What NOT to say (phrases that tend to escalate)\n4. How to end the conversation constructively even if it goes badly\n5. The most important thing to listen for"`,
          timeEstimate: '15 minutes',
          insight: 'Preparation is the difference between conflict and resolution. This works for manager feedback, client issues, co-founder disagreements, and family conversations.',
        },
        {
          day: 14,
          title: 'Week 2 Workflow Audit',
          task: 'Identify your biggest time-wasters and plan AI solutions.',
          prompt: `"I want to audit my work tasks and find AI opportunities. My typical week:\n\nTasks I do repeatedly: [list 5-10 recurring tasks]\nTasks that take too long: [list 2-3]\nTasks I avoid because they're tedious: [list 2-3]\n\nFor each task, tell me:\n1. Whether AI can help (yes/partially/no)\n2. If yes: the specific type of AI tool and a sample prompt to start\n3. Estimated time savings per week\n\nPrioritize by: highest time savings + easiest to implement."`,
          timeEstimate: '20 minutes',
          insight: 'After 2 weeks, you have enough AI experience to accurately identify where it helps most in YOUR specific workflow.',
        },
      ],
    },
    {
      week: 3,
      theme: 'AI for Personal Life: Health, Home & Goals',
      days: [
        {
          day: 15,
          title: 'Weekly Meal Planner',
          task: 'Generate a full week of meals and a complete shopping list.',
          prompt: `"Create a 7-day meal plan for [number] people. Dietary needs: [any restrictions]. Time available to cook: [weekdays: X minutes, weekends: X minutes]. Budget: [$X per week]. Cuisine preferences: [any].\n\nFor each day: Breakfast (5 min or less prep), Lunch (can be leftovers or simple), Dinner (full recipe).\n\nAlso generate: a complete shopping list organized by grocery store section."`,
          timeEstimate: '10 minutes',
          insight: "Meal planning with AI saves $100-200/month on food waste and eliminates the 'what's for dinner' decision fatigue.",
        },
        {
          day: 16,
          title: 'Fitness Plan Builder',
          task: 'Build a customized fitness plan.',
          prompt: `"Create a [X]-week fitness plan for me. My goal: [lose weight/build muscle/increase endurance/general fitness]. Current fitness level: [beginner/intermediate]. Equipment available: [none/dumbbells/full gym/etc]. Time per session: [X minutes]. Days per week I can commit: [X].\n\nFor each workout day: specific exercises with sets/reps/rest time. Include: warm-up routine, main workout, cool-down. Also give me: nutrition tip for this goal, one metric to track progress."`,
          timeEstimate: '10 minutes',
          insight: "AI fitness plans aren't a substitute for a trainer but are infinitely better than 'I should probably exercise.'",
        },
        {
          day: 17,
          title: 'Travel Planning in Minutes',
          task: 'Plan your next trip or dream destination.',
          prompt: `"Plan a [X-day] trip to [destination] for [number] people. Budget: [$X total or $X/day]. Travel style: [luxury/budget/adventure/cultural/relaxing]. Interests: [list 3-4 things you love]. Travel dates: [approximate season/month].\n\nProvide:\n- Day-by-day itinerary\n- Top 5 must-do activities with estimated cost\n- 3 restaurant recommendations per meal type (budget/mid/splurge)\n- Transportation tips between locations\n- 3 money-saving tips specific to this destination"`,
          timeEstimate: '15 minutes',
          insight: 'Verify restaurant and attraction details are current with a quick Google search before building plans around them.',
        },
        {
          day: 18,
          title: 'Budget & Finance Analyzer',
          task: 'Get an AI financial review of your current situation.',
          prompt: `"Help me understand my finances. My situation:\n- Monthly income: [$X]\n- Fixed expenses: [list: rent $X, car $X, subscriptions $X, etc]\n- Variable expenses (typical month): [food $X, entertainment $X, etc]\n- Savings goal: [what I'm saving for and when]\n- Current savings: [$X]\n\nTell me: Am I on track? Where are my biggest opportunities to save? What's the #1 financial move I should make this month? Create a simple monthly budget template for me."`,
          timeEstimate: '15 minutes',
          insight: "Never share your actual account numbers or SSN with AI. Estimates are fine for planning purposes.",
        },
        {
          day: 19,
          title: 'Learning Accelerator',
          task: 'Build your personal learning curriculum for any skill.',
          prompt: `"I want to learn [topic/skill] in [timeframe]. I have [X hours per week]. I learn best by [reading/watching/doing/discussing].\n\nCreate a curriculum with:\n- Week-by-week learning milestones\n- Best free resources for each milestone (YouTube channels, websites, books)\n- One practice project per week\n- How to know when I've mastered each milestone\n- The common mistake beginners make that wastes months of time"`,
          timeEstimate: '15 minutes',
          insight: "Start week 1 today — do the first recommended resource before the day ends or the plan stays theoretical.",
        },
        {
          day: 20,
          title: 'Gift Idea Generator',
          task: 'Never struggle with gift ideas again.',
          prompt: `"Help me find the perfect gift. Recipient: [relationship to you]. About them: [3-5 things they love, hobbies, interests, personality]. Budget: [$X]. Occasion: [birthday/holiday/thank you/etc]. What I want them to feel when they receive it: [surprised/appreciated/loved/excited].\n\nGive me: 10 gift ideas (5 physical, 3 experience-based, 2 digital/subscription). For each: estimated cost, where to buy, and one sentence on why they'll love it. Star your top 2 recommendations."`,
          timeEstimate: '10 minutes',
          insight: 'The more specific you are about the person, the better the suggestions. Generic prompts get generic answers.',
        },
        {
          day: 21,
          title: 'Life Admin Batcher',
          task: 'Batch all your life admin into one 15-minute session.',
          prompt: `"I need to write [X] messages/emails today. They are:\n1. [describe message 1: to whom, about what, desired tone]\n2. [describe message 2]\n3. [describe message 3]\n...\n\nWrite all [X] messages efficiently. After each one, note the best time to send it (if timing matters)."`,
          timeEstimate: '15 minutes',
          insight: 'Batching administrative tasks with AI turns a 2-hour afternoon into a 15-minute morning session.',
        },
      ],
    },
    {
      week: 4,
      theme: 'Advanced AI: Automation, Creation & Mastery',
      days: [
        {
          day: 22,
          title: 'Build a Personal AI Assistant Persona',
          task: 'Create a custom AI persona for your daily use.',
          prompt: `"I want to create a custom AI persona for my daily use. Based on this description of my work and needs:\n- I work as: [your role]\n- My biggest daily challenges: [list 2-3]\n- My communication style: [formal/casual/direct/detailed]\n- What I need AI to be best at: [list 3 things]\n\nCreate: A system prompt I can use at the start of every ChatGPT conversation to set up my personal assistant. It should define the AI's role, communication style, priorities, and what it should always/never do. Make it under 150 words."`,
          timeEstimate: '20 minutes',
          insight: 'Save this system prompt somewhere accessible. Paste it at the start of every new AI conversation to skip the warm-up phase.',
        },
        {
          day: 23,
          title: 'Content Repurposing Engine',
          task: 'Turn one piece of content into 13 pieces.',
          prompt: `"I have this piece of content:\n\n[paste your blog post, email, video script, etc]\n\nRepurpose it into:\n1. 3 LinkedIn posts (150-200 words each, different angles)\n2. 5 Twitter/X posts (under 250 chars each, punchy)\n3. 1 Instagram caption (storytelling format, 100-150 words, 10 hashtags)\n4. 1 email newsletter section (conversational, 200 words, CTA at end)\n5. 3 key quotes for graphics\n\nMaintain the core message but adapt completely for each platform's culture."`,
          timeEstimate: '15 minutes',
          insight: "One strong piece of original content plus this prompt equals a week's worth of social media material.",
        },
        {
          day: 24,
          title: 'AI for Creative Projects',
          task: 'Get brutally honest creative feedback on any project.',
          prompt: `"I'm working on a creative project: [describe it — writing, art concept, business idea, invention, event, etc].\n\nI need creative input on:\n1. The concept — what's strong and what's weak\n2. 5 unexpected directions I haven't considered\n3. What would make this unforgettable vs merely good\n4. One bold creative risk worth taking\n5. The most common mistake people make with this type of project\n\nBe honest, not just encouraging."`,
          timeEstimate: '15 minutes',
          insight: "Ask AI to be 'honest, not just encouraging' — without this instruction it defaults to cheerleading.",
        },
        {
          day: 25,
          title: 'Multi-Step Workflow Design',
          task: 'Automate your most repetitive task.',
          prompt: `"Help me design an automated workflow for this repeating task:\n\nTask: [describe what you currently do manually]\nFrequency: [how often it happens]\nInputs: [what triggers it]\nOutputs: [what the finished result looks like]\nTools I use: [list any apps you use]\n\nDesign the workflow:\n1. Map the current manual steps\n2. Identify which steps can be automated (and with what tool)\n3. Identify which steps require human judgment\n4. Show me the ideal automated version\n5. Tell me what to set up first"`,
          timeEstimate: '20 minutes',
          insight: 'Most people discover their most repetitive task can be 80% automated. The 20% requiring human judgment is where your real value lives.',
        },
        {
          day: 26,
          title: 'Strategic Life Planning',
          task: 'Get an honest life strategy session.',
          prompt: `"Help me do a strategic life review.\n\nMy situation:\n- Current role/work: [describe]\n- What I want in 3 years: [career, lifestyle, finances, relationships]\n- What I'm proud of from the last year: [2-3 things]\n- What I'm not happy with: [2-3 things]\n- My biggest opportunity right now: [what I think it is]\n- My biggest obstacle: [what's holding me back]\n\nGive me:\n1. An honest assessment of my trajectory\n2. The #1 thing to change in the next 90 days\n3. A skill gap I should address\n4. What I might be undervaluing about my current situation\n5. Three-question framework to make better decisions going forward"`,
          timeEstimate: '20 minutes',
          insight: "AI gives you honest assessment without social awkwardness. It won't spare your feelings, which is exactly what strategic planning requires.",
        },
        {
          day: 27,
          title: 'AI Prompt Engineering Master Class',
          task: 'Level up your prompt engineering skills.',
          prompt: `"Teach me advanced prompt engineering in a practical, hands-on way. I want to learn:\n1. The anatomy of a perfect prompt (with a framework)\n2. Chain-of-thought prompting and when to use it\n3. How to get consistent formatting every time\n4. The 5 most powerful techniques that most people don't know\n5. One prompt template I can use to test any AI model's capabilities\n\nFor each technique, give me a before/after example showing the difference it makes."`,
          timeEstimate: '20 minutes',
          insight: 'After 27 days of practice, advanced techniques will click immediately. You have enough context to understand why they work.',
        },
        {
          day: 28,
          title: 'Build Your AI Toolkit',
          task: 'Design your permanent AI toolkit.',
          prompt: `"Based on everything I've described about my work and life this month — [summarize your main use cases for AI from days 1-27] — help me design my personal AI toolkit.\n\nFor each tool I need, tell me:\n1. The best free option\n2. The best paid option (and whether it's worth it)\n3. The exact use case it solves\n4. How long to get value from it (learning curve)\n\nGroup them by: Must-Have (use daily), Nice-to-Have (weekly), Worth Exploring (monthly)."`,
          timeEstimate: '20 minutes',
          insight: "The goal isn't to use every AI tool — it's to use the right 3-5 tools extremely well.",
        },
        {
          day: 29,
          title: 'Teach AI to Teach You',
          task: 'Master any concept using the Feynman technique.',
          prompt: `"I want to deeply understand [topic or skill I'm still confused about]. Don't just explain it — teach it to me using the Feynman technique:\n1. Explain it like I'm 12 years old (the simplest possible version)\n2. Now explain it at an intermediate level\n3. Give me an analogy from daily life\n4. Show me where the common misconceptions lead people astray\n5. Give me a test: 3 questions I should now be able to answer\n\nAfter I attempt the test questions in my head, ask me if I want feedback."`,
          timeEstimate: '20 minutes',
          insight: "If you can't explain it simply, you don't understand it yet. This technique forces genuine understanding over surface familiarity.",
        },
        {
          day: 30,
          title: 'Your 30-Day Reflection & Next Chapter',
          task: 'Complete your transformation review.',
          prompt: `"I've completed 30 days of daily AI practice. Here are my notes on what worked:\n[paste your notes, favorite prompts, biggest wins]\n\nHelp me:\n1. Identify my top 5 AI superpowers (what I'm best at now)\n2. Calculate my rough time savings per week\n3. Design my ongoing AI routine (what to do daily, weekly, monthly)\n4. Name 3 new AI capabilities to develop in the next 30 days\n5. Write a before/after description of how I use AI — to share with someone who's curious"`,
          timeEstimate: '20 minutes',
          insight: "Congratulations on completing the 30-Day AI Challenge. You've built habits that most professionals won't develop for years. Keep going — AI capabilities are growing monthly, and so is your competitive advantage.",
        },
      ],
    },
  ],
};
