export const PRODUCT_005 = {
  id: '005',
  title: 'Ultimate AI Cheat Sheet Bundle',
  subtitle: '7 Printable Reference Cards for ChatGPT, Claude, Midjourney & More',
  type: 'cheat-sheet' as const,
  niche: 'ai-tools',
  targetAudience: 'AI users at any level wanting quick reference material',
  pages: 14,
  wordCount: 5000,
  fileFormats: ['PDF'] as string[],
  price: 6.99,
  sheets: [
    {
      number: 1,
      title: 'ChatGPT Power User Reference',
      promptFormulas: [
        'Act as [expert]: "Act as a senior [role] with 20 years of experience. Analyze..."',
        'CLEAR Framework: [C]ontext + [L]ength + [E]xamples + [A]sk + [R]ole',
        'Step-by-step: "Think through this step by step before answering..."',
        'Format control: "Return as: numbered list / table / bullet points / JSON"',
        'Iteration: "Good, now make it: shorter / more formal / more specific about X"',
        'Chain: "Based on that output, now create..."',
        "Devil's advocate: \"What are the 5 strongest arguments against this?\"",
        'Calibrate: "Rate your confidence in this answer from 1-10 and explain why"',
        "Simplify: \"Explain this like I'm 10, then like I'm an expert\"",
        'Verify: "What sources would you check to verify these claims?"',
      ],
      powerMoves: [
        '"Continue" — resumes a cut-off response',
        '"Be more specific about [X]" — drills into any point',
        '"Now make a checklist" — converts any content into action steps',
        '"What am I missing?" — surfaces blindspots',
        '"Add concrete examples" — makes abstract ideas tangible',
        '"What are the counterarguments?" — builds critical thinking',
        '"Translate to plain English" — removes jargon',
        '"Now write it for [different audience]" — adapts tone',
      ],
      doNotDo: [
        'Never share passwords, SSNs, full credit card numbers',
        'Never paste confidential contracts or trade secrets',
        'Always fact-check statistics and recent events',
        "Don't use AI output verbatim for medical or legal decisions",
        "Don't assume AI has current information (training data has cutoffs)",
      ],
      models: {
        'GPT-4o': 'Best reasoning, image analysis, complex tasks',
        'GPT-4o mini': 'Fast, cheap, great for simple tasks and high volume',
        'o1 / o1-mini': 'Deep reasoning, math, logic — slower but more accurate',
      },
    },
    {
      number: 2,
      title: 'Claude AI Reference Card',
      strengths: [
        'Long documents: Analyzes up to 200,000 tokens (150,000+ words)',
        'Coding: Writes clean, well-commented code with explanations',
        'Analysis: Nuanced reasoning with multiple perspectives',
        'Writing: Natural, less-robotic output than GPT for creative work',
        'Safety: Better at refusing genuinely harmful requests while being helpful',
      ],
      uniqueTechniques: [
        'XML tags: <task>...</task> <context>...</context> for structured prompts',
        "Prefill: \"I'll analyze this in 3 parts:\" — Claude continues the pattern",
        'Thinking: Ask "think step by step" for complex problems',
        'Persona: "You are [expert]. Your goal is [X]. User: [question]"',
        'Document analysis: Paste full PDFs (up to 100 pages) for analysis',
      ],
      bestUseCases: [
        'Analyzing long contracts, reports, or research papers',
        'Complex coding projects with multiple files',
        'Nuanced ethical or strategic questions requiring balance',
        'Long-form writing that needs to sound human',
        'Summarizing and extracting insights from huge documents',
      ],
      pricingNotes: 'claude.ai free tier: limited daily usage. Claude Pro ($20/month): priority access, more usage. API: pay per token.',
    },
    {
      number: 3,
      title: 'Midjourney Prompt Formula',
      anatomy: '/imagine [subject] [style] [composition] [lighting] [color] [--parameters]',
      subjects: [
        'a photorealistic portrait of',
        'an isometric illustration of',
        'a watercolor painting of',
        'a 3D render of',
        'a flat design vector of',
      ],
      styles: [
        'in the style of [artist]',
        'cinematic',
        'editorial photography',
        'concept art',
        'anime',
        'art nouveau',
        'brutalist',
        'minimalist',
      ],
      lighting: [
        'golden hour',
        'studio lighting',
        'dramatic chiaroscuro',
        'soft diffused light',
        'neon glow',
        'backlit silhouette',
      ],
      parameters: {
        '--ar 16:9': 'Widescreen (YouTube thumbnails, banners)',
        '--ar 9:16': 'Vertical (Instagram Reels, TikTok)',
        '--ar 1:1': 'Square (Instagram posts)',
        '--ar 4:5': 'Portrait (Instagram feed)',
        '--v 6': 'Latest model (best quality)',
        '--q 2': 'Higher quality (slower, more credits)',
        '--s 750': 'Medium stylization (0=natural, 1000=max artistic)',
        '--no [element]': 'Exclude something from the image',
        '--chaos 50': 'More variation between results (0-100)',
        '--seed [number]': 'Reproduce similar results',
      },
      examplePrompts: [
        'Professional headshot, confident woman entrepreneur, 40s, natural smile, soft studio lighting, shallow depth of field, Canon 85mm, photorealistic --ar 1:1 --v 6',
        'Modern minimalist logo for a tech startup, geometric shapes, midnight blue and electric orange, vector style, white background --ar 1:1 --v 6 --no gradients',
        'Cozy home office setup, warm lighting, plants, macbook on wooden desk, flat lay, editorial photography style --ar 4:5 --v 6',
      ],
    },
    {
      number: 4,
      title: 'Universal AI Prompt Formulas',
      formulas: [
        {
          name: 'The Expert Ask',
          template: '"Act as a [expert type] with [X years] experience in [field]. [Your question or task]."',
          when: 'Any specialized topic',
        },
        {
          name: 'The Before/After',
          template: '"Here is [before: current version]. Rewrite it to be [desired improvement]."',
          when: 'Improving existing content',
        },
        {
          name: 'The Framework Builder',
          template: '"Create a framework/checklist/template for [process]. It should work for [audience] and address [specific challenge]."',
          when: 'Creating reusable systems',
        },
        {
          name: 'The Socratic Method',
          template: '"Ask me 5 questions that will help me clarify my thinking on [topic]. After I answer, give your analysis."',
          when: 'Clarifying your own thoughts',
        },
        {
          name: 'The Competitor Lens',
          template: '"Analyze this from the perspective of [my competitor/skeptic/customer]. What would they say is wrong with this?"',
          when: 'Stress-testing ideas',
        },
        {
          name: 'The Scenario Planner',
          template: '"If [situation], what would the best outcome look like? What steps lead there? What could go wrong?"',
          when: 'Planning and risk assessment',
        },
        {
          name: 'The Constraint Creator',
          template: '"Complete this task with these constraints: [constraint 1], [constraint 2]. Task: [X]."',
          when: 'Need creative solutions or concise output',
        },
        {
          name: 'The Teach-Back',
          template: '"Teach me [topic]. Then ask me 3 questions to test my understanding. Then give me feedback on my answers."',
          when: 'Actually learning something',
        },
      ],
    },
    {
      number: 5,
      title: 'AI Tools Comparison Matrix',
      tools: [
        {
          name: 'ChatGPT-4o',
          price: 'Free / $20/mo',
          bestFor: 'General tasks, coding, image analysis',
          contextWindow: '128K tokens',
          weakness: 'Can be verbose',
        },
        {
          name: 'Claude 3.5 Sonnet',
          price: 'Free / $20/mo',
          bestFor: 'Long docs, nuanced writing, coding',
          contextWindow: '200K tokens',
          weakness: 'No image generation',
        },
        {
          name: 'Google Gemini',
          price: 'Free / $20/mo',
          bestFor: 'Google Workspace integration, real-time info',
          contextWindow: '1M tokens',
          weakness: 'Inconsistent quality',
        },
        {
          name: 'Microsoft Copilot',
          price: 'Free / $20/mo (M365)',
          bestFor: 'Office integration, web search, images',
          contextWindow: 'Variable',
          weakness: 'Limited without M365',
        },
        {
          name: 'Perplexity AI',
          price: 'Free / $20/mo',
          bestFor: 'Research with citations, current info',
          contextWindow: 'Variable',
          weakness: 'Not great for creative tasks',
        },
        {
          name: 'Midjourney',
          price: '$10-60/mo',
          bestFor: 'Professional image generation',
          contextWindow: 'N/A',
          weakness: 'Discord-based, learning curve',
        },
        {
          name: 'DALL-E 3',
          price: 'Included in ChatGPT+',
          bestFor: 'Quick image generation, logo concepts',
          contextWindow: 'N/A',
          weakness: 'Less artistic than Midjourney',
        },
      ],
    },
    {
      number: 6,
      title: 'Top 20 Business AI Prompts',
      prompts: [
        'Cold email: "Write a cold email to [role] at [company type] about [offer]. Under 100 words, one CTA, personalized opening."',
        'Meeting agenda: "Create a 45-min meeting agenda for [topic] with [attendees]. Include time allocations and pre-read materials."',
        'Pricing: "Help me price [product/service] for [market]. Analyze: competitor pricing, value delivered, psychological pricing tactics."',
        'Data: "I have this data: [paste data]. What are the 3 most important insights? What should I do differently based on this?"',
        'Pitch: "Write an elevator pitch for [company/idea] in 30 seconds. Open with the problem, middle with the solution, close with the ask."',
        'Job post: "Write a job description for [role] that attracts A-players and deters poor fits. Include: real challenges, growth opportunities, culture."',
        'Research: "Research [company/competitor] for me. Find: business model, revenue model, key customers, recent news, weaknesses I can exploit."',
        'Launch: "Write a product launch announcement email for [product]. Create urgency, highlight the #1 benefit, include social proof."',
        'Partnership: "Draft an email proposing a partnership between [company A] and [company B]. Explain the mutual benefit clearly."',
        'Content: "Create 1 month of [platform] content for [business]. Mix: educational, promotional, entertaining, engaging. One post per day."',
        'SOP: "Write a standard operating procedure for [process]. Step by step, with decision points and what to do when something goes wrong."',
        'Funnel: "Design a 5-email nurture sequence for leads interested in [product]. Each email: subject, preview text, body, CTA."',
        'Review: "Write a response to this [positive/negative] customer review: [paste review]. Professional, personal, and action-oriented."',
        "Report: \"Turn these numbers into an executive summary: [paste metrics]. Focus on what changed, why it matters, what we're doing about it.\"",
        'Hiring: "Write 10 interview questions for [role] that reveal: problem-solving ability, culture fit, technical skills, and coachability."',
        'Ideation: "Generate 15 business ideas in [industry/niche]. For each: target customer, revenue model, unfair advantage needed."',
        'Product: "Write a product description for [product] that sells. Lead with the transformation, not the features. Max 200 words."',
        "Decision: \"I'm deciding between [A] and [B]. Help me think through it: pros/cons, hidden considerations, what I'll regret not choosing.\"",
        "Debug: \"This [process/strategy/code] isn't working as expected. Here's what's happening: [describe]. What are the 5 most likely causes?\"",
        'Proposal: "Write a project proposal for [client] for [service]. Include: understanding of their problem, proposed solution, timeline, investment, why us."',
      ],
    },
    {
      number: 7,
      title: 'AI Safety & Ethics Quick Guide',
      neverShare: [
        'Social Security / National ID numbers',
        'Passwords or login credentials',
        'Full credit/debit card numbers',
        'Medical records (use general descriptions)',
        'Legal case details with client names',
        'Confidential business contracts',
        'Internal financial data (use approximate numbers)',
      ],
      alwaysVerify: [
        'Statistics and data points',
        'Recent events (training data has cutoffs)',
        'Medical and legal advice',
        'Product specifications and prices',
        'Scientific research claims',
        'Historical dates and facts in detail',
      ],
      workplacePolicies: [
        "Check your company's AI use policy before using work data in AI",
        'Use company-approved AI tools for sensitive projects',
        'Never paste customer PII into public AI tools',
        'Disclose AI assistance when required by your industry',
        'Keep AI-generated code reviewed by humans before production',
      ],
      biasAwareness: [
        'AI reflects biases in its training data',
        'Always consider diverse perspectives on sensitive topics',
        "AI can confidently be wrong — confidence does not equal accuracy",
        'Controversial topics may receive politically-influenced responses',
        'Ask for multiple viewpoints on complex issues',
      ],
    },
  ],
};
