import { Product, Bundle, AnalyticsData, DashboardStats, Keyword, ResearchData, AutomationTask } from './types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'AI Insurance Agent Toolkit',
    description: 'Complete AI-powered toolkit for insurance agents including scripts, templates, and automation prompts to close more deals and streamline operations.',
    type: 'prompt-pack',
    status: 'active',
    price: 27,
    compareAtPrice: 47,
    etsyListingId: 'listing-001',
    etsyListingUrl: 'https://etsy.com/listing/001',
    tags: ['insurance agent', 'AI prompts', 'sales scripts', 'ChatGPT', 'insurance templates'],
    category: 'Templates',
    subcategory: 'Business Templates',
    contents: ['250+ ChatGPT Prompts', 'Cold Call Scripts', 'Email Templates', 'Objection Handlers', 'Follow-up Sequences', 'Underwriting Checklist'],
    chapters: ['Getting Started with AI', 'Lead Generation Prompts', 'Sales Conversations', 'Policy Explanations', 'Claims Assistance'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Insurance+Toolkit'],
    salesCopy: 'Transform your insurance business with AI. Close 3x more deals in half the time.',
    revenue: 4320,
    sales: 160,
    views: 12400,
    favorites: 892,
    conversionRate: 1.29,
    avgRating: 4.9,
    reviewCount: 87,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'AI Agency-in-a-Box',
    description: 'Launch your own AI consulting agency with this complete business system including client onboarding, service packages, pricing guides, and 500+ AI prompts.',
    type: 'bundle',
    status: 'active',
    price: 97,
    compareAtPrice: 197,
    tags: ['AI agency', 'consulting business', 'freelance', 'ChatGPT business', 'digital agency'],
    category: 'Templates',
    subcategory: 'Business Templates',
    contents: ['Business Plan Template', 'Service Package Deck', 'Client Contracts', '500+ AI Prompts', 'Pricing Calculator', 'Proposal Templates', 'Onboarding Checklist'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Agency+in+a+Box'],
    salesCopy: 'Start your 6-figure AI agency this week. Everything you need, nothing you don\'t.',
    revenue: 12620,
    sales: 130,
    views: 18900,
    favorites: 1240,
    conversionRate: 0.69,
    avgRating: 4.8,
    reviewCount: 112,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
  },
  {
    id: '3',
    name: 'Small Business AI Automation Bundle',
    description: 'AI automation playbook for small business owners. Cut operations time by 70% with ready-to-use prompts, workflows, and SOPs for every department.',
    type: 'pdf',
    status: 'active',
    price: 37,
    compareAtPrice: 67,
    tags: ['small business', 'AI automation', 'business operations', 'productivity', 'SOPs'],
    category: 'Templates',
    subcategory: 'Business Templates',
    contents: ['Marketing Automation Prompts', 'Customer Service Scripts', 'HR Automation Templates', 'Financial SOP Guides', 'Operations Checklists', 'Weekly Review Templates'],
    chapters: ['Introduction to AI Automation', 'Marketing & Sales', 'Operations & Admin', 'Customer Success', 'Finance & Reporting'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Automation+Bundle'],
    revenue: 7030,
    sales: 190,
    views: 22100,
    favorites: 1560,
    conversionRate: 0.86,
    avgRating: 4.7,
    reviewCount: 143,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: '4',
    name: 'AI Content Creation System',
    description: 'Complete content marketing system powered by AI. Generate months of content in hours with 300+ prompts for blogs, social media, email, and video scripts.',
    type: 'prompt-pack',
    status: 'active',
    price: 29,
    compareAtPrice: 49,
    tags: ['content creation', 'AI writing', 'social media', 'blog prompts', 'content marketing'],
    category: 'Templates',
    subcategory: 'Marketing Templates',
    contents: ['300+ Content Prompts', 'Content Calendar Template', 'Blog Outline Generator', 'Social Media Templates', 'Email Sequences', 'YouTube Script Templates'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Content+System'],
    revenue: 5510,
    sales: 190,
    views: 28700,
    favorites: 2100,
    conversionRate: 0.66,
    avgRating: 4.9,
    reviewCount: 201,
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-03-12T00:00:00Z',
  },
  {
    id: '5',
    name: 'AI Recruiting & Hiring Toolkit',
    description: 'Revolutionize your hiring process with AI. Includes job description generators, interview question banks, evaluation frameworks, and onboarding templates.',
    type: 'spreadsheet',
    status: 'active',
    price: 47,
    compareAtPrice: 87,
    tags: ['recruiting', 'hiring', 'HR templates', 'job descriptions', 'interview questions'],
    category: 'Spreadsheets',
    subcategory: 'Business & Finance',
    contents: ['Applicant Tracking Sheet', 'Job Description Generator', '500+ Interview Questions', 'Scoring Rubrics', 'Offer Letter Templates', 'Onboarding Checklist'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Recruiting+Toolkit'],
    revenue: 6580,
    sales: 140,
    views: 14200,
    favorites: 980,
    conversionRate: 0.99,
    avgRating: 4.8,
    reviewCount: 96,
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-03-08T00:00:00Z',
  },
  {
    id: '6',
    name: 'AI Fitness Coach Business Pack',
    description: 'Launch your online fitness coaching business with AI. Includes client assessment templates, workout plan generators, nutrition guides, and 200+ coaching prompts.',
    type: 'bundle',
    status: 'active',
    price: 67,
    compareAtPrice: 127,
    tags: ['fitness coach', 'personal trainer', 'online coaching', 'workout plans', 'nutrition'],
    category: 'Templates',
    subcategory: 'Health & Wellness',
    contents: ['Client Assessment Forms', 'Workout Plan Templates', 'Nutrition Guide Generator', '200+ Coaching Prompts', 'Progress Tracking Sheet', 'Marketing Scripts'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Fitness+Coach+Pack'],
    revenue: 8710,
    sales: 130,
    views: 16800,
    favorites: 1320,
    conversionRate: 0.77,
    avgRating: 4.9,
    reviewCount: 118,
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: '7',
    name: 'AI Side Hustle Starter Kit',
    description: 'Start and grow 5 profitable AI side hustles with this complete starter kit. Includes business models, scripts, templates, and step-by-step launch guides.',
    type: 'pdf',
    status: 'active',
    price: 19,
    compareAtPrice: 37,
    tags: ['side hustle', 'passive income', 'AI business', 'make money online', 'entrepreneur'],
    category: 'Templates',
    subcategory: 'Business Templates',
    contents: ['5 Business Model Guides', 'Launch Checklist', 'Marketing Templates', 'Pricing Calculator', 'Client Scripts', 'Scaling Roadmap'],
    chapters: ['Freelance AI Writing', 'AI Social Media Management', 'Prompt Engineering Services', 'AI Video Creation', 'AI Consulting'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Side+Hustle+Kit'],
    revenue: 3610,
    sales: 190,
    views: 31200,
    favorites: 2890,
    conversionRate: 0.61,
    avgRating: 4.7,
    reviewCount: 234,
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-03-18T00:00:00Z',
  },
  {
    id: '8',
    name: 'Sports Betting Research Toolkit',
    description: 'Data-driven sports betting research system with statistical models, bankroll management spreadsheets, and AI analysis prompts for serious bettors.',
    type: 'spreadsheet',
    status: 'active',
    price: 37,
    compareAtPrice: 67,
    tags: ['sports betting', 'betting strategy', 'bankroll management', 'sports analytics', 'betting research'],
    category: 'Spreadsheets',
    subcategory: 'Sports',
    contents: ['Bankroll Tracker', 'Bet Logging Sheet', 'Statistical Model Templates', 'Research Prompts', 'Value Betting Calculator', 'Season Performance Dashboard'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=Sports+Betting+Toolkit'],
    revenue: 5180,
    sales: 140,
    views: 19400,
    favorites: 1670,
    conversionRate: 0.72,
    avgRating: 4.6,
    reviewCount: 89,
    createdAt: '2024-02-25T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  },
  {
    id: '9',
    name: 'Notion AI Business Operating System',
    description: 'Complete Notion workspace for running an AI-powered business. Includes CRM, project management, content calendar, financial dashboard, and team wiki.',
    type: 'notion',
    status: 'active',
    price: 47,
    compareAtPrice: 97,
    tags: ['Notion template', 'business OS', 'CRM', 'project management', 'productivity'],
    category: 'Templates',
    subcategory: 'Productivity Templates',
    contents: ['Client CRM Database', 'Project Management Board', 'Content Calendar', 'Financial Dashboard', 'Team Wiki', 'Goal Tracking System', 'AI Prompt Library'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=Notion+Business+OS'],
    revenue: 9870,
    sales: 210,
    views: 24600,
    favorites: 2240,
    conversionRate: 0.85,
    avgRating: 4.9,
    reviewCount: 267,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-03-22T00:00:00Z',
  },
  {
    id: '10',
    name: 'AI Business Growth Vault',
    description: 'The ultimate premium bundle containing ALL our best-selling AI business tools. 1,000+ prompts, 50+ templates, and complete business systems in one vault.',
    type: 'bundle',
    status: 'active',
    price: 197,
    compareAtPrice: 497,
    tags: ['AI business', 'business bundle', 'ChatGPT prompts', 'business templates', 'entrepreneur'],
    category: 'Templates',
    subcategory: 'Business Templates',
    contents: ['All 9 Product Systems', '1000+ AI Prompts', '50+ Business Templates', 'Exclusive Masterclass', 'Private Community Access', 'Lifetime Updates'],
    mockupUrls: ['https://placehold.co/600x400/1a1a3e/ffffff?text=AI+Business+Growth+Vault'],
    salesCopy: 'Everything you need to build a 6-figure AI business. 60% off for a limited time.',
    revenue: 18230,
    sales: 92,
    views: 8900,
    favorites: 1890,
    conversionRate: 1.03,
    avgRating: 5.0,
    reviewCount: 78,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-03-25T00:00:00Z',
  },
]

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  todayRevenue: 842,
  weeklyRevenue: 5240,
  monthlyRevenue: 22140,
  annualRevenue: 81660,
  totalProducts: 10,
  activeListings: 10,
  totalSales: 1474,
  avgConversionRate: 0.85,
  revenueGrowth: 23.4,
  salesGrowth: 18.7,
}

export const MOCK_ANALYTICS: AnalyticsData[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date()
  date.setDate(date.getDate() - (29 - i))
  return {
    period: date.toISOString().split('T')[0],
    revenue: Math.floor(Math.random() * 1200 + 400),
    orders: Math.floor(Math.random() * 18 + 5),
    views: Math.floor(Math.random() * 800 + 200),
    favorites: Math.floor(Math.random() * 40 + 10),
    conversionRate: Math.random() * 0.8 + 0.4,
    avgOrderValue: Math.floor(Math.random() * 40 + 45),
  }
})

export const MOCK_KEYWORDS: Keyword[] = [
  { term: 'AI prompts for business', searchVolume: 8200, competition: 'medium', relevanceScore: 95, trend: 'up' },
  { term: 'ChatGPT templates', searchVolume: 12400, competition: 'high', relevanceScore: 88, trend: 'up' },
  { term: 'digital download business', searchVolume: 6700, competition: 'medium', relevanceScore: 82, trend: 'stable' },
  { term: 'Notion template business', searchVolume: 9100, competition: 'medium', relevanceScore: 90, trend: 'up' },
  { term: 'AI business tools', searchVolume: 5400, competition: 'low', relevanceScore: 94, trend: 'up' },
  { term: 'prompt pack etsy', searchVolume: 3200, competition: 'low', relevanceScore: 98, trend: 'up' },
  { term: 'spreadsheet templates', searchVolume: 18900, competition: 'high', relevanceScore: 75, trend: 'stable' },
  { term: 'side hustle digital product', searchVolume: 7600, competition: 'medium', relevanceScore: 86, trend: 'up' },
]

export const MOCK_BUNDLES: Bundle[] = [
  {
    id: 'b1',
    name: 'AI Entrepreneur Mega Bundle',
    description: 'Top 5 AI business products at 50% off',
    productIds: ['1', '2', '3', '4', '7'],
    price: 97,
    originalPrice: 209,
    savings: 112,
    status: 'active',
    revenue: 4850,
    sales: 50,
    createdAt: '2024-02-01T00:00:00Z',
  },
]

export const MOCK_AUTOMATIONS: AutomationTask[] = [
  { id: 'a1', name: 'Daily SEO Refresh', description: 'Update titles and tags for underperforming listings', trigger: 'scheduled', schedule: '0 9 * * *', lastRun: '2024-03-25T09:00:00Z', status: 'success', category: 'seo' },
  { id: 'a2', name: 'Weekly Content Batch', description: 'Generate 7 days of Pinterest and social content', trigger: 'scheduled', schedule: '0 8 * * 1', lastRun: '2024-03-25T08:00:00Z', status: 'success', category: 'content' },
  { id: 'a3', name: 'Competitor Price Monitor', description: 'Check competitor pricing and alert on significant changes', trigger: 'scheduled', schedule: '0 12 * * *', lastRun: '2024-03-25T12:00:00Z', status: 'success', category: 'research' },
  { id: 'a4', name: 'Review Response Generator', description: 'Draft responses to new customer reviews', trigger: 'event', lastRun: '2024-03-24T15:30:00Z', status: 'idle', category: 'content' },
  { id: 'a5', name: 'Monthly Analytics Report', description: 'Generate comprehensive performance report', trigger: 'scheduled', schedule: '0 9 1 * *', status: 'idle', category: 'analytics' },
  { id: 'a6', name: 'Product Expansion Suggestions', description: 'AI-powered suggestions for new product variations', trigger: 'manual', status: 'idle', category: 'content' },
]
